name = "quiz-site-api"
main = "src/index.js"
compatibility_date = "2026-06-03"

routes = [
  { pattern = "net-pr-re-quiz.m15tak3.com/api/*", zone_name = "m15tak3.com" }
]

[vars]
APP_URL = "https://net-pr-re-quiz.m15tak3.com"
ALLOWED_ORIGINS = "https://net-pr-re-quiz.m15tak3.com"
GITHUB_CLIENT_ID = "Ov23liQgJHaIfBzE8QkN"

[[d1_databases]]
binding = "DB"
database_name = "quiz_site"
database_id = "85d19b3f-83cb-4000-aed6-6e329e0af085"
